fileName <- "household_power_consumption.txt"
db <- read.table(fileName, header = TRUE, sep = ";", na.strings = "?")
db$Date <- strptime(db$Date, "%d/%m/%Y")
db$Date <- as.Date(db$Date)
db1 <- filter(db, between(Date, as.Date("2007-02-01"), as.Date("2007-02-02")))
db1$datetime = with(db1, as.POSIXct(paste(Date, Time), format="%Y-%m-%d %H:%M:%S"))
png(filename = "plot4.png", width = 480, height = 480)
par(mfrow = c(2,2))
with(db1, plot(datetime, Global_active_power, type = "l", xlab = "", ylab = "Global Active Power", main = NULL))
with(db1, plot(datetime, Voltage, type = "l", xlab = "datetime", ylab = "Voltage", main = NULL))
with(db1, plot(datetime, Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering", main = NULL))
lines(db1$datetime, db1$Sub_metering_2, type = "l", col = 2)
lines(db1$datetime, db1$Sub_metering_3, type = "l", col = 4)
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c(1, 2, 4), lty=1, bty = "n")
with(db1, plot(datetime, Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power", main = NULL))
dev.off()